language: node_js

node_js:
  - "0.10"

script: gulp

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
  target_branch: gh-pages
